//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronics_Selling_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECOMMERCE_VIEW
    {
        public int User_ID { get; set; }
        public string User_FirstName { get; set; }
        public string User_LastName { get; set; }
        public string User_Email { get; set; }
        public int odid { get; set; }
        public System.DateTime od_date { get; set; }
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public int unitprice { get; set; }
        public int o_qty { get; set; }
        public decimal o_bill { get; set; }
        public string Product_CategoryName { get; set; }
    }
}
