//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronics_Selling_System
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;

    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_Product = new HashSet<tbl_Product>();
            this.tbl_OrderDetails = new HashSet<tbl_OrderDetails>();
        }
    
        public int User_ID { get; set; }
        public string User_FirstName { get; set; }
        public string User_LastName { get; set; }
        public string User_Phone { get; set; }
        public string User_Email { get; set; }
        public string User_Gender { get; set; }
        public string User_Password { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string User_Address { get; set; }
        public int Role_ID { get; set; }
        public System.DateTime User_Dob { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Product> tbl_Product { get; set; }
        public virtual tbl_RoleName tbl_RoleName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderDetails> tbl_OrderDetails { get; set; }
        public int GetPassword()
        {
            SqlCommand sq_com = new SqlCommand("loginmember", Connections.GetConnection());
            sq_com.CommandType = CommandType.StoredProcedure;

            sq_com.Parameters.AddWithValue("@User_Email", User_Email);
            SqlDataAdapter sda = new SqlDataAdapter(sq_com);

            DataTable dt = new DataTable();
            sda.Fill(dt);
            if (dt.Rows.Count > 0)
                if (dt.Rows[0][0].Equals(User_Password))
                {
                    User_FirstName = dt.Rows[0][2].ToString();
                    User_ID = Convert.ToInt32(dt.Rows[0][3]);
                    if (dt.Rows[0][1].Equals(1))
                    {
                        return 1;
                    }
                    return 2;
                }
            return -1;
        }
    }
}
