//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronics_Selling_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Orders
    {
        public int oid { get; set; }
        public System.DateTime odate { get; set; }
        public int o_qty { get; set; }
        public int unitprice { get; set; }
        public decimal o_bill { get; set; }
        public int Product_ID { get; set; }
        public int odid { get; set; }
    
        public virtual tbl_OrderDetails tbl_OrderDetails { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
